### ISSUE TITLE
Cpol_DIA modules

### ISSUE THREAD

**Issue by doragasu** [JoanTheSpark/KiCAD#1]
Thanks for your great work with these modules.

I cloned this repo and started browsing through the ZIP files, but I cannot find the Cpol_DIAXXXX modules that appear on the photograph. Where can I find them?

Also I'd like to make a request. Could it be possible for future updates, to upload the modules without zipping them? It would make updating (pulling) the repo a lot easier and faster.

**Comment by JoanTheSpark** [comment]
You're welcome.

Oh, the picture was a screenshot of the CAD tool that I use to make those models.. must not have uploaded them then.
At the moment I'm in the process of going through the models again, so I'll reaorganize/rename some and get the VRML file size down considerably thanks to Maurice's work in that area..
You can see updates on this here: https://forum.kicad.info/t/3d-new-library-for-mechanical-cad-exporting-and-enclosure-design/1763/156

Also, Maurice got a FreeCAD python script that does put out SMD alu capacitors that look pretty similar to the ones I make (just in case you're desparate and don't want to wait on me with my models):
https://github.com/easyw/kicad-3d-models-in-freecad/blob/master/cadquery/FCAD_script_generator/parametric-aluminum-capacitors.png

As for zips vs single files.. I had them first as single files in repos, but most wanted them in zips..
I'll probably do that then as the file sizes got 10 times smaller to what they are now, should be no big deal.

**Comment by doragasu** [comment]
Thanks for the detailed response!

I'll close the issue and have a look to that script.

Good to see you continue working on this. Thanks!
